/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.p-b-10[_ngcontent-%COMP%]{\r\n    padding-bottom: 10px\r\n}\r\n.m-b-20[_ngcontent-%COMP%]{\r\n     margin-bottom: 20px\r\n}\r\n.whitBox[_ngcontent-%COMP%]{\r\n    padding:25px;\r\n    box-shadow: 0 1px 4px 0 rgba(0, 0, 0, 0.1);\r\n    margin-top: 15%\r\n}\r\n.box-title[_ngcontent-%COMP%]{\r\n    font-size: 16px;\r\n    font-weight:bold;\r\n}\r\nlabel[_ngcontent-%COMP%]{\r\n    font-weight:100\r\n}\r\nbutton[_ngcontent-%COMP%]{\r\n    border-radius:10px\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvamVjdHMvbWVhbi9zcmMvYXBwL2xvZ2luL2xvZ2luLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovcHJvamVjdHMvbWVhbi9zcmMvYXBwL2xvZ2luL2xvZ2luLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
