/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/new-vote/new-vote.module';
import * as i2 from './new-vote.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/router';
import * as i6 from '../../../../src/app/new-vote/new-vote.component';
export const NewVoteModuleNgFactory:i0.NgModuleFactory<i1.NewVoteModule> = i0.ɵcmf(i1.NewVoteModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.NewVoteComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i4.FormBuilder,i4.FormBuilder,([] as any[])),i0.ɵmpd(4608,i4.ɵi,i4.ɵi,
              ([] as any[])),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,([] as any[])),
          i0.ɵmpd(512,i5.RouterModule,i5.RouterModule,[[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,
              i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.ReactiveFormsModule,i4.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i1.NewVoteModule,i1.NewVoteModule,([] as any[])),
          i0.ɵmpd(1024,i5.ROUTES,() => {
            return [[{path:'',component:i6.NewVoteComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvamVjdHMvbWVhbi9zcmMvYXBwL25ldy12b3RlL25ldy12b3RlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9wcm9qZWN0cy9tZWFuL3NyYy9hcHAvbmV3LXZvdGUvbmV3LXZvdGUubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
